# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://www.blog.philodev.one"
defaultContentLanguage = "en"

enableRobotsTXT = true
pagerSize = 10
summaryLength = 0

title = "Sofia Fischer; Philodev"
copyright = "© 2026 Sofia Fischer. Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"

dateFormat = "2 January 2006"

[outputs]
  home = ["HTML", "RSS", "JSON", "ATOM"]

[taxonomies]
  tag = "tags"

[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]
[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "atom" # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false