languageCode = "en"
languageName = "English"
weight = 1

[params]
    rtl = false
    isoCode = "en"
    displayName = "EN"
    description = "The thoughts and ideas of a Developer about coding, development process and self improvement"

dateFormat = "2 January 2006"

