languageCode = "en"
languageName = "English"
weight = 1

[params]
    rtl = false
    isoCode = "en"
    displayName = "EN"
    description = "The thoughts and ideas of a Code Wizard about coding, development process and self improvement"

title = "Philodev Blog"

[header]
    logo = "logo.png"

# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params.author]
  name = "Sofia Fischer"
  # image = "img/author.jpg"
  headline = "Philomathic Developer"
  # bio = "A little bit about me"
  links = [
    { email = "mailto:sofia@philodev.com" },
    { link = "https://www.philodev.one" },
    { github = "https://github.com/sofia-fischer" },
    { linkedin = "https://www.linkedin.com/in/sofia-fischer-58b1611b9/" },
  ]
