# This is a basic workflow to help you get started with Actions

name: Deploy to Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # The first step is provided by GitHub and it checks out 
    # the master branch on the runner
    - uses: actions/checkout@master
      with:
        submodules: true
    
    # This step uses an action created by a user which sets
    # up Hugo on the runner and runs the hugo command to build
    # the site
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.98.0'
          
    - name: Build
      run: hugo --minify
      
	  # The last step deploys the site to my server by running 
	  # the deploy script located in the ci directory 
	  # within the repo
    - name: deploy
      run: source $GITHUB_WORKSPACE/ci/deploy.sh
      env:
	      # This section sets up the environment used by the 
	      # deploy script. These values are injected from 
	      # the repo's secret store
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        SSH_USERNAME: ${{ secrets.HETZNER_SSH_USERNAME }}
        SERVER_ADDRESS: ${{ secrets.HETZNER_SSH_HOST }}
        SERVER_DESTINATION: "/home/${{ secrets.HETZNER_SSH_USERNAME }}/dev/philo-blog/"
        SSH_PORT: ${{ secrets.HETZNER_SSH_PORT }}
